language: node_js
node_js:
- node

cache:
  directories:
  - node_modules

script:
- npm install -g serverless

before_install:
- openssl aes-256-cbc -K $encrypted_21be0bbb01f1_key -iv $encrypted_21be0bbb01f1_iv
  -in cits-3200-abc14d0972cf.json.enc -out cits-3200-abc14d0972cf.json -d

deploy:
  provider: gae
  keyfile: cits-3200-abc14d0972cf.json
  project: cits-3200

